version: '3.3'
services: 
    elasticsearch_node1:
        container_name: elasticsearch_node1
        image: elasticsearch:7.13.2
        ports: 
            - 9200:9200
            - 9300:9300
        environment:
            discovery.type: single-node
        
        volumes:
           -  ./elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
           -  ./data:/usr/share/elasticsearch/data
    
    kibana:
        container_name: kibana
        image: docker.elastic.co/kibana/kibana:7.13.2
        ports: 
            - 5601:5601
        environment: 
            ELASTICSEARCH_HOSTS: http://elasticsearch_node1:9200